name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - rolling
        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ros:foxy
            ros_distribution: foxy

          # Galactic Geochelone (May 2021 - November 2022)
          - docker_image: ros:galactic
            ros_distribution: galactic

          # Rolling Ridley (No End-Of-Life)
          - docker_image: ros:rolling
            ros_distribution: rolling
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update apt
        run: |
          apt update
          apt upgrade -y
          apt install -y python3-pip

      - name: Install python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install git+https://github.com/PyCQA/pyflakes.git --upgrade
          pip3 install pylint flake8 pytest bandit mypy  --upgrade

      - name: Install ROS dependencies
        run: |
          echo "yaml https://gitlab.com/eufs/eufs_rosdep/-/raw/master/python.yaml" >> /etc/ros/rosdep/sources.list.d/19-eufs.list
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y --rosdistro=${{ matrix.ros_distribution }}
          
      - name: Lint with flake8
        run: |
          source /opt/ros/galactic/setup.bash
          python3 -m flake8 . --max-line-length=100

      - name: Lint with pylint
        run: |
          source /opt/ros/galactic/setup.bash
          git config --global --add safe.directory /__w/rtk_mapper/rtk_mapper
          python3 -m pylint $(git ls-files '*.py') --max-line-length=100 --fail-under=9

      - name: Check security with bandit
        run: |
          python3 -m bandit -r .

      - name: Test with pytest
        run: |
          python3 -m pytest
