name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: ["3.8.12", "3.10.4"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python $${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: $${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 pytest bandit

      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=100

      - name: Lint with pylint
        run: |
          pylint $(git ls-files '*.py') --max-line-length=100

      - name: Check security with bandit
        run: |
          bandit -r .

      - name: Test with pytest
        run: |
          pytest
