name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - galactic
          - humble
        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ros:foxy
            ros_distribution: foxy
            python-version: "3.8"
            ros_version: 2

          # Galactic Geochelone (May 2021 - November 2022)
          - docker_image: ros:galactic
            ros_distribution: galactic
            python-version: "3.8"
            ros_version: 2

          # Rolling Ridley (No End-Of-Life)
          - docker_image: ros:rolling
            ros_distribution: rolling
            python-version: "3.10"
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint flake8 pytest bandit

      - name: Install ROS dependencies
        run: |
          echo "yaml https://gitlab.com/eufs/eufs_rosdep/-/raw/master/python.yaml" >> /etc/ros/rosdep/sources.list.d/19-eufs.list
          rosdep update
          rosdep install --ignore-src --from-paths src -r -y --rosdistro=${{ matrix.ros_distribution }}
          
      - name: Lint with flake8
        run: |
          python3 -m flake8 . --max-line-length=100

      - name: Lint with pylint
        run: |
          python3 -m pylint $(git ls-files '*.py') --max-line-length=100

      - name: Check security with bandit
        run: |
          python3 -m bandit -r .

      - name: Test with pytest
        run: |
          python3 -m pytest
